CREATE DATABASE SISTEMAFUNCODE;

USE SISTEMAFUNCODE

CREATE TABLE USUARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NIKC_NAME VARCHAR (100),
	SENHA VARCHAR (100)NOT NULL,
	IDADE INT (2)
);


CREATE TABLE MODULO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	MODULO VARCHAR (100)
);


CREATE TABLE NIVEIS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NIVEL VARCHAR (100)

);


CREATE TABLE EXERCICIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FASE VARCHAR(100),
    ID_NIVEIS INT,
    FOREIGN KEY (ID_NIVEIS) REFERENCES NIVEIS(ID)
);


CREATE TABLE PROGRESSO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	STATUS BOOLEAN DEFAULT(false),
	ID_MODULO INT,
	ID_EXERCICIO INT,
	FOREIGN KEY (ID_MODULO)  REFERENCES MODULO (ID),	
	FOREIGN KEY (ID_EXERCICIO)  REFERENCES EXERCICIO (ID)
);


CREATE TABLE TRILHA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO INT,
	ID_PROGRESSO INT,
	FOREIGN KEY (ID_USUARIO)  REFERENCES USUARIO (ID),	
	FOREIGN KEY (ID_PROGRESSO)  REFERENCES PROGRESSO (ID)
);







/*Usuario*/

INSERT INTO USUARIO (NIKC_NAME, SENHA, IDADE) VALUES ('JOAO', 'senha1', 25);
INSERT INTO USUARIO (NIKC_NAME, SENHA, IDADE) VALUES ('AKON', 'senha2', 30);
INSERT INTO USUARIO (NIKC_NAME, SENHA, IDADE) VALUES ('DIDI', 'senha3', 22);
INSERT INTO USUARIO (NIKC_NAME, SENHA, IDADE) VALUES ('POST MALONE', 'senha4', 28);
INSERT INTO USUARIO (NIKC_NAME, SENHA, IDADE) VALUES ('STAN LEE', 'senha5', 35);



/*MODULO*/
INSERT INTO MODULO (MODULO) VALUES
('LOGICA DE PROGRAMACAO'),
('PYTHON'),
('HTML'),
('CSS'),
('JAVASCRIPT');


/*NIVEL*/

INSERT INTO NIVEIS (NIVEL) VALUES ('Fácil');
INSERT INTO NIVEIS (NIVEL) VALUES ('Intermediario');
INSERT INTO NIVEIS (NIVEL) VALUES ('Avançado');


/*EXERCICIO*/

INSERT INTO EXERCICIO (FASE, ID_NIVEIS) VALUES
('Sequência de Comandos', 1),
('Condicionais if/else', 1),
('Laços de Repetição Loop', 1),
('Entrada e Saída de dados', 1),
('Variáveis', 1),
('Comparação Simples', 1),
('Depuração Básica', 1),
('Condicionais Aninhadas', 2),
('Loops com Contador', 2),
('Funções', 2),
('Manipulação de String', 2),
('Lógica Booleana', 2),
('Introdução de Arrays / Listas', 2),
('Depuração Avançada', 2),
('Funções Recursivas', 3),
('Busca e Ordenação', 3),
('Algoritmos de Divisão e Conquista', 3),
('Lógica Proposicional', 3),
('Otimização de Código', 3),
('Algoritmos de Busca', 3),
('Análise de Complexidade', 3);


/*PROGRESSO*/
INSERT INTO PROGRESSO (ID_MODULO,ID_EXERCICIO, STATUS) VALUES
(1,1,TRUE),
(1,2,FALSE),
(1,3,TRUE),
(1,4,FALSE),
(1,5,TRUE),
(1,6,FALSE),
(1,7,TRUE),

(1,8,TRUE),
(1,9,FALSE),
(1,10,TRUE),
(1,11,FALSE),
(1,12,TRUE),
(1,13,FALSE),
(1,14,TRUE),

(1,15,TRUE),
(1,16,FALSE),
(1,17,TRUE),
(1,18,FALSE),
(1,19,TRUE),
(1,20,FALSE),
(1,21,TRUE);



/*TRILHA*/
INSERT INTO TRILHA (ID_USUARIO,ID_PROGRESSO) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);




/*Selecionar todos os usuários*/


SELECT * FROM USUARIO;

/*Selecionar todos os módulos*/


SELECT * FROM MODULO;

/*Selecionar todos os níveis*/


SELECT * FROM NIVEIS;


/*Selecionar todos os exercícios com seus níveis*/

SELECT E.ID, E.FASE, N.NIVEL 
FROM EXERCICIO E
JOIN NIVEIS N ON E.ID_NIVEIS = N.ID;

/*Selecionar o progresso de cada exercício*/


SELECT P.ID, M.MODULO, E.FASE, P.STATUS 
FROM PROGRESSO P
JOIN MODULO M ON P.ID_MODULO = M.ID
JOIN EXERCICIO E ON P.ID_EXERCICIO = E.ID;

/*Selecionar trilhas de usuários com progresso*/


SELECT T.ID AS TRILHA_ID, U.NIKC_NAME, P.STATUS
FROM TRILHA T
JOIN USUARIO U ON T.ID_USUARIO = U.ID
JOIN PROGRESSO P ON T.ID_PROGRESSO = P.ID;


/*Contar quantos exercícios estão completos por módulo*/


SELECT M.MODULO, COUNT(P.STATUS) AS EXERCICIOS_COMPLETOS
FROM PROGRESSO P
JOIN MODULO M ON P.ID_MODULO = M.ID
WHERE P.STATUS = TRUE
GROUP BY M.MODULO;


/*Selecionar usuários com idade acima de 30 anos*/

SELECT * FROM USUARIO WHERE IDADE > 30;



/*TABELA TRILHA COM DADOS DO USUARIO E PROGRESSO */


SELECT T.ID AS TRILHA_ID, U.NIKC_NAME,P.ID AS PROGRESSO_ID
FROM TRILHA T
JOIN USUARIO U ON T.ID_USUARIO = U.ID
JOIN PROGRESSO P ON T.ID_PROGRESSO = P.ID;



/*TABELA TRILHA, NOME DO USUARIO, MODULO, FASE*/

SELECT T.ID AS Trilha_ID, U.NIKC_NAME, M.MODULO, E.FASE
FROM TRILHA T
JOIN USUARIO U ON T.ID_USUARIO = U.ID
JOIN PROGRESSO P ON T.ID_PROGRESSO = P.ID
JOIN MODULO M ON P.ID_MODULO = M.ID
JOIN EXERCICIO E ON P.ID_EXERCICIO = E.ID;


/*TABELA TRILHA, NOME DO USUARIO, MODULO, FASE, STATUS*/

SELECT T.ID AS Trilha_ID, U.NIKC_NAME, M.MODULO, E.FASE, P.STATUS
FROM TRILHA T
JOIN USUARIO U ON T.ID_USUARIO = U.ID
JOIN PROGRESSO P ON T.ID_PROGRESSO = P.ID
JOIN MODULO M ON P.ID_MODULO = M.ID
JOIN EXERCICIO E ON P.ID_EXERCICIO = E.ID;